server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditosdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

azure:
  servicebus:
    connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING:}
    topic-name: ${AZURE_SERVICEBUS_TOPIC_NAME:}
    subscription-name: ${AZURE_SERVICEBUS_SUBSCRIPTION_NAME:}
    enabled: ${AZURE_SERVICEBUS_ENABLED:true}
    processor:
      enabled: ${AZURE_SERVICEBUS_PROCESSOR_ENABLED:false}
